### ISSUE TITLE
Add ability to specify stream name on ffmpeg_hls

### ISSUE THREAD

**Issue by jamesbirtles** [KallDrexx/mmids#27]
For similar reasons that you would want a different stream key for rtmp watch, it would be great to be able to provide a different name for the m3u8 and ts files to ffmpeg_hls

Would you accept a PR for this? I can see that you intend to replace the ffmpeg steps at some point.

**Comment by KallDrexx** [comment]
That makes sense to me, I would definitely accept a PR for that.

While I want to depreciate ffmpeg, I have to add the replacement parts to it first and currently busy with webrtc and some other features, so it'll be a while.  That being said, any additions that get added to the ffmpeg steps before then will be transferred over, so your PR will make sure I add the customized name feature in the new work.
